name: iOS CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List simulators
        run: xcrun simctl list devices available

      - name: Build and test
          run: |
            xcodebuild test \
              -project FinanceFlow.xcodeproj \
              -scheme FinanceFlow \
              -destination 'id=61AE1FC1-A43D-439B-92B0-FAB4CE70C7CE' \
              -enableCodeCoverage YES
